### PR TITLE
Add Snake.

### PR DESCRIPTION
**Pull request by Dev0Louis**
Snake is normal Snake.
Bad Snake is Snake with Bad apple background.

### CODE REVIEW

**Comment by Benonardo** [comment]
Not a fan of bad snake personally, seems a bit unnecessary.

**Comment by BasiqueEvangelist** [comment]
good snake :+1:

**Comment by Dev0Louis** [comment]
I've removed bad snake.
And changed a few things. 
Should be ready to merge.

**Comment by enjarai** [comment]
Sneykey

**Pull request merged**
